use_frameworks!
platform :ios, '9.0'

target 'EFFlukyProgressHUD_Example' do
  pod 'EFFlukyProgressHUD', :path => '../'

  target 'EFFlukyProgressHUD_Tests' do
    inherit! :search_paths

    
  end
end
