language: objective-c
osx_image: xcode10.2
env: SWIFT_SNAPSHOT=5.0

cache: cocoapods
podfile: Example/Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=Example/EFFlukyProgressHUD.xcworkspace
  matrix:
    - SCHEME="EFFlukyProgressHUD-Example"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Example

script:
  - set -o pipefail
  - pod repo update
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - pod lib lint --allow-warnings

after_success:
  - sleep 3